import "./global.scss";
import type { Metadata } from "next";
import classNames from "classnames";
import { font_dm_sans, font_inter } from "@/library/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={classNames(font_dm_sans.variable, font_inter.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
